name: CI -> Deploy to Github Pages
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: cs2pr, phpcs
      - run: cd generate_content && php composer.phar install
      - run: php generate_content/importtransform.php
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 'v16.13.1'
      - run: npm install
      - run: npm run build
      - run: npm run generate
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.